version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  node:
    image: node:12
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: ${DATABASE_URL}
      JWT_SECRET: burgerapi
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: changeme
    volumes:
      - ./:/home/node/app
    expose:
      - 8080
    ports:
      - 80:8080
    command: bash -c 'rm -rf node_modules && npm install && npm start'
    depends_on:
      - db
    networks:
      - public
      - private
networks:
  public:
    internal: false
  private:
    internal: true
