version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=diego
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=db_burger
    ports:
      - "5432:5432"
    volumes:
      - ./db-data-1:/var/lib/postgresql/data

  node:
    image: node:12
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: ${DATABASE_URL}
      JWT_SECRET: burgerapi
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: changeme
    volumes:
      - ./:/home/node/app
    expose:
      - 8080
    ports:
      - 8080:8080
    command: bash -c 'rm -rf node_modules && npm install && npm start'
    depends_on:
      - postgres
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "diego@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pass123"
    ports:
      - 80:80
    depends_on:
      - postgres
